version: '3.4'

services:

  apigateway:
    image: envoyproxy/envoy:v1.16.5
    container_name: apigateway
    restart: always

  #backoffice:
  #  image: ${DOCKER_REGISTRY:-schoolmngr}/backoffice:${PLATFORM:-linux}-${TAG:-dev}
  #  container_name: backoffice
  #  build:
  #    context: .
  #    dockerfile: microservices/admin/SchoolMngr.Services.Backoffice/Dockerfile
  #  depends_on:
  #    - postgressql
  #    - rabbitmq

  #academe:
  #  image: ${DOCKER_REGISTRY:-schoolmngr}/academe:${PLATFORM:-linux}-${TAG:-dev}
  #  container_name: academe
  #  build:
  #    context: .
  #    dockerfile: microservices/academe/SchoolMngr.Services.Academe/Dockerfile
  #  depends_on:
  #    - postgressql
  #    - rabbitmq

  notifications:
    image: ${DOCKER_REGISTRY:-schoolmngr}/notifications:${PLATFORM:-linux}-${TAG:-dev}
    container_name: notifications
    build:
      context: .
      dockerfile: microservices/notifications/SchoolMngr.Services.Notifications/Dockerfile
    depends_on:
      - msbroker

  sqldb:
    image: postgres
    container_name: sqldb
    restart: always

  nosqldb:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
     container_name: nosqldb

  kibana:
     image: docker.elastic.co/kibana/kibana:7.14.1
     container_name: kibana

  msbroker:
     image: rabbitmq:3.9.5-management
     container_name: msbroker

networks:
  esnet:

volumes:
  postgressql-data:
  elasticsearch-data: